name: Deploy FastAPI on Main Updates

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-fastapi:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d "${{ secrets.APPS_FOLDER }}/${{ secrets.APP_NAME }}/.git" ]; then
              echo "Repo not found. Cloning..."
              cd ${{ secrets.APPS_FOLDER }}
              git clone ${{ secrets.REPO_URL }} ${{ secrets.APP_NAME }}
              cd ${{ secrets.APP_NAME }}
            else
              echo "Repo exists. Pulling latest changes..."
              cd "${{ secrets.APPS_FOLDER }}/${{ secrets.APP_NAME }}"
              git pull
            fi

            sudo apt update
            sudo apt install -y python3-venv python3-pip

            # Create venv if missing
            if [ ! -d "${{ secrets.APPS_FOLDER }}/${{ secrets.APP_NAME }}/venv" ]; then
              echo "Creating virtual environment..."
              cd "${{ secrets.APPS_FOLDER }}/${{ secrets.APP_NAME }}"
              python3 -m venv venv
            fi

            # Activate venv & install dependencies
            cd "${{ secrets.APPS_FOLDER }}/${{ secrets.APP_NAME }}"
            source venv/bin/activate
            pip install -r requirements.txt

            # # Restart service
            # sudo systemctl restart fastapi
